### ISSUE TITLE
事隔两年，大神有没想法弄成手机版或者微信小游戏

### ISSUE THREAD

**Issue by cheft** [LiuJi-Jim/h5pal#10]
事隔两年，大神有没想法弄成手机版或者微信小游戏

**Comment by LiuJi-Jim** [comment]
手机版据悉已经有了，反正安卓是早就有了好多个版本，都是基于SDLPAL的，iOS可能没有。
微信小游戏的话应该因为版权问题不太可能做到，而且到现在游戏音频也没做，完成度不够。

**Comment by cheft** [comment]
我刚刚把音频的弄了一下，貌似可以了，只是87个音频文件有点大

**Comment by cheft** [comment]
方便加个好友吗，QQ 7720829 我是做前端开发的。

**Comment by LiuJi-Jim** [comment]
嗯，播MP3音轨的话还是很简单的，不过追求原汁原味的话还是midi或者rix吧。我后来抄了一个日本人的项目可以在web里播放midi了，不过没有功夫整合到仙剑里面来。
