### ISSUE TITLE
 http://localhost:8005/pal-assets/desc.dat  找不到

### ISSUE THREAD

**Issue by Mickey-** [LiuJi-Jim/h5pal#5]
![image](https://cloud.githubusercontent.com/assets/2062355/10185544/bad7f9cc-677b-11e5-9105-9952e37104ad.png)
如图，还有这个问题

**Comment by wileam** [comment]
看 readme：

> 建立pal-assets/目录，把仙剑95版（存档180~185KB的版本）的所有文件拷贝进去。（不要问我去哪里找）

（p.s. 好巧

**Comment by Mickey-** [comment]
太巧了！你也情怀粉？

历经艰苦下到了，都拷贝进去了，但是好像就缺这个文件，求分享~
